export const CAT_BREED_GALLERY_IMAGES: Record<string, string[]> = {
  "american-shorthair": [
    "/images/cat-breeds/american-shorthair-cozy.jpg",
    "/images/cat-breeds/american-shorthair-outdoor.jpg",
    "/images/cat-breeds/american-shorthair-silver.jpg",
    "/images/cat-breeds/american-shorthair-tabby.jpg",
    "/images/cat-breeds/american-shorthair.jpg",
  ],
  "bengal": [
    "/images/cat-breeds/bengal-athletic.jpg",
    "/images/cat-breeds/bengal-full.jpg",
    "/images/cat-breeds/bengal-golden.jpg",
    "/images/cat-breeds/bengal-rosette.jpg",
    "/images/cat-breeds/bengal-spots.jpg",
    "/images/cat-breeds/bengal.jpg",
  ],
  "british-shorthair": [
    "/images/cat-breeds/british-shorthair-blue.jpg",
    "/images/cat-breeds/british-shorthair-cozy.jpg",
    "/images/cat-breeds/british-shorthair-golden.jpg",
    "/images/cat-breeds/british-shorthair-silver.jpg",
  ],
  "devon-rex": [
    "/images/cat-breeds/devon-rex-bicolor.jpg",
    "/images/cat-breeds/devon-rex-coat.jpg",
    "/images/cat-breeds/devon-rex-cream.jpg",
    "/images/cat-breeds/devon-rex-lilac.jpg",
    "/images/cat-breeds/devon-rex-outdoor.jpg",
    "/images/cat-breeds/devon-rex.jpg",
  ],
  "exotic-shorthair": [
    "/images/cat-breeds/exotic-shorthair-bicolor.jpg",
    "/images/cat-breeds/exotic-shorthair-cozy.jpg",
    "/images/cat-breeds/exotic-shorthair-cream.jpg",
    "/images/cat-breeds/exotic-shorthair-tabby.jpg",
    "/images/cat-breeds/exotic-shorthair.jpg",
  ],
  "maine-coon": [
    "/images/cat-breeds/maine-coon-face.jpg",
    "/images/cat-breeds/maine-coon-full.jpg",
    "/images/cat-breeds/maine-coon-group.jpg",
    "/images/cat-breeds/maine-coon-portrait.jpg",
    "/images/cat-breeds/maine-coon-silver.jpg",
    "/images/cat-breeds/maine-coon.jpg",
  ],
  "mix-shorthair": [
    "/images/cat-breeds/mix-shorthair-black.jpg",
    "/images/cat-breeds/mix-shorthair-orange.jpg",
    "/images/cat-breeds/mix-shorthair-portrait.jpg",
    "/images/cat-breeds/mix-shorthair-tabby.jpg",
    "/images/cat-breeds/mix-shorthair-tuxedo.jpg",
    "/images/cat-breeds/mix-shorthair.jpg",
  ],
  "munchkin": [
    "/images/cat-breeds/munchkin-bicolor.jpg",
    "/images/cat-breeds/munchkin-play.jpg",
    "/images/cat-breeds/munchkin-standing.jpg",
    "/images/cat-breeds/munchkin-tabby.jpg",
    "/images/cat-breeds/munchkin.jpg",
  ],
  "norwegian-forest": [
    "/images/cat-breeds/norwegian-forest-outdoor.jpg",
    "/images/cat-breeds/norwegian-forest-pack.jpg",
    "/images/cat-breeds/norwegian-forest-portrait.jpg",
    "/images/cat-breeds/norwegian-forest-snow.jpg",
    "/images/cat-breeds/norwegian-forest.jpg",
  ],
  "persian": [
    "/images/cat-breeds/persian-cozy.jpg",
    "/images/cat-breeds/persian-cream.jpg",
    "/images/cat-breeds/persian-face.jpg",
    "/images/cat-breeds/persian-fluffy.jpg",
    "/images/cat-breeds/persian-portrait.jpg",
    "/images/cat-breeds/persian.jpg",
  ],
  "ragdoll": [
    "/images/cat-breeds/ragdoll-mitted.jpg",
    "/images/cat-breeds/ragdoll.jpg",
  ],
  "russian-blue": [
    "/images/cat-breeds/russian-blue-cozy.jpg",
    "/images/cat-breeds/russian-blue-elegant.jpg",
    "/images/cat-breeds/russian-blue-paw.jpg",
    "/images/cat-breeds/russian-blue-portrait.jpg",
    "/images/cat-breeds/russian-blue-pose.jpg",
    "/images/cat-breeds/russian-blue-window.jpg",
    "/images/cat-breeds/russian-blue.jpg",
  ],
  "scottish-fold": [
    "/images/cat-breeds/scottish-fold-cozy.jpg",
    "/images/cat-breeds/scottish-fold-outdoor.jpg",
    "/images/cat-breeds/scottish-fold-studio.jpg",
    "/images/cat-breeds/scottish-fold-tabby.jpg",
    "/images/cat-breeds/scottish-fold-white.jpg",
    "/images/cat-breeds/scottish-fold.jpg",
  ],
  "siamese": [
    "/images/cat-breeds/siamese-blue.jpg",
    "/images/cat-breeds/siamese-chocolate.jpg",
    "/images/cat-breeds/siamese-classic.jpg",
    "/images/cat-breeds/siamese-portrait.jpg",
    "/images/cat-breeds/siamese-seal.jpg",
    "/images/cat-breeds/siamese.jpg",
  ],
  "sphynx": [
    "/images/cat-breeds/sphynx-calico.jpg",
    "/images/cat-breeds/sphynx-kitten.jpg",
    "/images/cat-breeds/sphynx-portrait.jpg",
    "/images/cat-breeds/sphynx-profile.jpg",
    "/images/cat-breeds/sphynx-tuxedo.jpg",
    "/images/cat-breeds/sphynx.jpg",
  ],
};
