"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useI18n } from "@/lib/i18n/I18nProvider";
import { petSchema } from "@/lib/account/validation";

type PetRow = { id: string; name: string; species: "dog" | "cat"; birthday: string | null; breed: string; allergy_ingredients: string[]; special_notes: string };
type PetForm = { name: string; species: "dog" | "cat"; birthday: string; breed: string; allergies: string; specialNotes: string };
const EMPTY: PetForm = { name: "", species: "dog", birthday: "", breed: "", allergies: "", specialNotes: "" };
const inputClass = "min-h-12 w-full rounded-xl border border-[color:var(--line)] bg-white px-3.5 py-3 text-base outline-none focus:border-[color:var(--accent)] sm:text-sm";

export function PetProfileManager() {
  const { locale } = useI18n(); const en = locale === "en";
  const [pets, setPets] = useState<PetRow[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState<PetForm>(EMPTY); const [editingId, setEditingId] = useState<string | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/account/pets", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(); setPets(data.pets ?? []); setError(""); } catch { setError(en ? "Unable to load pet profiles." : "毛孩檔案暫時無法載入。 "); } finally { setLoading(false); } }, [en]);
  useEffect(() => { void load(); }, [load]);
  const set = (key: keyof PetForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  function edit(pet: PetRow) { setEditingId(pet.id); setForm({ name: pet.name, species: pet.species, birthday: pet.birthday ?? "", breed: pet.breed ?? "", allergies: (pet.allergy_ingredients ?? []).join(", "), specialNotes: pet.special_notes ?? "" }); setError(""); setNotice(""); }
  function reset() { setEditingId(null); setForm(EMPTY); setError(""); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const parsed = petSchema.safeParse({ name: form.name, species: form.species, birthday: form.birthday, breed: form.breed, allergyIngredients: form.allergies.split(/[,，、]/).map((v) => v.trim()).filter(Boolean), specialNotes: form.specialNotes }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? (en ? "Check the profile fields." : "請檢查檔案資料。")); return; } const response = await fetch(editingId ? `/api/account/pets/${editingId}` : "/api/account/pets", { method: editingId ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(parsed.data) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error); await load(); reset(); setNotice(en ? "Pet profile saved." : "毛孩檔案已儲存。"); } catch { setError(en ? "Could not save the profile. Check required fields." : "儲存失敗，請檢查必填欄位。 "); } finally { setBusy(false); } }
  async function remove(pet: PetRow) { if (!window.confirm(en ? `Delete ${pet.name}'s profile?` : `確定刪除 ${pet.name} 的檔案？`)) return; setBusy(true); try { const response = await fetch(`/api/account/pets/${pet.id}`, { method: "DELETE" }); if (!response.ok) throw new Error(); await load(); setNotice(en ? "Pet profile deleted." : "毛孩檔案已刪除。"); } catch { setError(en ? "Could not delete this profile." : "刪除失敗，請稍後再試。 "); } finally { setBusy(false); } }
  return <div className="space-y-5">
    {loading ? <div className="grid gap-3 sm:grid-cols-2"><div className="h-36 animate-pulse rounded-2xl bg-stone-100" /><div className="h-36 animate-pulse rounded-2xl bg-stone-100" /></div> : pets.length ? <div className="grid gap-3 sm:grid-cols-2">{pets.map((pet) => <article key={pet.id} className="rounded-2xl border border-[color:var(--line)] bg-white p-4"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[color:var(--accent-soft)] text-xl" aria-hidden="true">{pet.species === "cat" ? "🐈" : "🐕"}</span><div><h2 className="font-semibold">{pet.name}</h2><p className="text-xs text-[color:var(--muted)]">{pet.species === "cat" ? (en ? "Cat" : "貓咪") : (en ? "Dog" : "狗狗")} {pet.breed ? `· ${pet.breed}` : ""}{pet.birthday ? ` · ${pet.birthday}` : ""}</p></div></div>{pet.allergy_ingredients?.length ? <p className="mt-3 text-sm leading-5"><span className="font-medium">{en ? "Allergies:" : "過敏食材："}</span><span className="text-[color:var(--muted)]">{pet.allergy_ingredients.join("、")}</span></p> : null}{pet.special_notes ? <p className="mt-2 break-words text-sm leading-5 text-[color:var(--muted)]">{pet.special_notes}</p> : null}<div className="mt-3 flex gap-2"><button type="button" disabled={busy} onClick={() => edit(pet)} className="min-h-11 rounded-xl border border-[color:var(--line)] px-3 text-sm">{en ? "Edit" : "編輯"}</button><button type="button" disabled={busy} onClick={() => void remove(pet)} className="min-h-11 rounded-xl border border-red-200 px-3 text-sm text-red-700">{en ? "Delete" : "刪除"}</button></div></article>)}</div> : <p className="rounded-2xl border border-dashed border-[color:var(--line)] bg-white p-5 text-sm leading-6 text-[color:var(--muted)]">{en ? "Add your pet's profile to record dietary needs and allergies." : "建立毛孩檔案，記錄生日、品種、過敏食材及特殊體質。"}</p>}
    <section className="rounded-2xl border border-[color:var(--line)] bg-white p-4 sm:p-6"><h2 className="text-lg font-semibold">{editingId ? (en ? "Edit pet" : "編輯毛孩檔案") : (en ? "Add a pet" : "新增毛孩檔案")}</h2><form onSubmit={submit} className="mt-4 space-y-4">
      <div className="grid gap-3 sm:grid-cols-2"><label className="block space-y-1.5"><span className="text-sm font-medium">{en ? "Pet's name" : "毛孩名字"} *</span><input className={inputClass} required maxLength={80} value={form.name} onChange={(event) => set("name", event.target.value)} /></label><label className="block space-y-1.5"><span className="text-sm font-medium">{en ? "Species" : "犬／貓"} *</span><select className={inputClass} value={form.species} onChange={(event) => set("species", event.target.value as "dog" | "cat")}><option value="dog">{en ? "Dog" : "狗狗"}</option><option value="cat">{en ? "Cat" : "貓咪"}</option></select></label></div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="block space-y-1.5"><span className="text-sm font-medium">{en ? "Birthday" : "生日"}</span><input className={inputClass} type="date" value={form.birthday} onChange={(event) => set("birthday", event.target.value)} /></label><label className="block space-y-1.5"><span className="text-sm font-medium">{en ? "Breed" : "品種"}</span><input className={inputClass} maxLength={100} value={form.breed} onChange={(event) => set("breed", event.target.value)} /></label></div>
      <label className="block space-y-1.5"><span className="text-sm font-medium">{en ? "Allergies / ingredients to avoid" : "過敏食材／需避免成分"}</span><input className={inputClass} maxLength={1000} value={form.allergies} onChange={(event) => set("allergies", event.target.value)} placeholder={en ? "Separate items with commas" : "以逗號分隔，例如：雞肉、牛奶"} /></label>
      <label className="block space-y-1.5"><span className="text-sm font-medium">{en ? "Special health or dietary notes" : "特殊體質／備註"}</span><textarea className={`${inputClass} min-h-24 resize-y`} maxLength={2000} value={form.specialNotes} onChange={(event) => set("specialNotes", event.target.value)} /></label>
      {error ? <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p> : null}{notice ? <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p> : null}
      <div className="flex flex-wrap gap-2"><button type="submit" disabled={busy} className="min-h-12 rounded-xl bg-[color:var(--accent)] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy ? (en ? "Saving…" : "儲存中…") : editingId ? (en ? "Save changes" : "儲存修改") : (en ? "Save pet profile" : "儲存毛孩檔案")}</button>{editingId ? <button type="button" disabled={busy} onClick={reset} className="min-h-12 rounded-xl border border-[color:var(--line)] px-5 py-3 text-sm">{en ? "Cancel" : "取消"}</button> : null}</div>
    </form></section>
  </div>;
}
