/**
 * Auto-generated by scrape_wt_japan.py — do not edit by hand.
 * Source: https://www.wt-japan.com/collections/貓罐罐/罐罐
 */

export type WtJapanProduct = {
  id: string;
  title: string;
  /** Storefront price in HKD (as listed on WT Japan). */
  price: number;
  /** Local path under /public for the downloaded hero image. */
  imageUrl: string;
  /** Original remote CDN URL used for the download. */
  sourceImageUrl: string;
  /** Plain-text description / ingredients (HTML stripped). */
  description: string;
  vendor: string;
  tags: string[];
  handle: string;
  productType: string;
  sourceUrl: string;
};

export const WT_JAPAN_PRODUCTS: WtJapanProduct[] = [
  {
    id: "wt-product-1",
    title: "CIAO 貓罐罐 - 鰹魚 帆立貝 85g x 6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-1.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133061684.jpg?v=1583201240",
    description: "賞味期限3年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "帆立貝", "綠茶消臭成分", "罐罐", "鰹魚"],
    handle: "ciao-貓罐罐-鰹魚-帆立貝-85g-x-6個",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-鰹魚-帆立貝-85g-x-6個",
  },
  {
    id: "wt-product-2",
    title: "CIAO 貓罐罐 - 白肉金槍魚、金槍魚乾、金槍魚汁 85g　x6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-2.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133062278.jpg?v=1583200361",
    description: "賞味期限 3年",
    vendor: "CIAO",
    tags: ["INABA", "綠茶消臭成分", "罐罐", "貓貓小食", "金槍魚"],
    handle: "ciao-貓罐罐-白肉金槍魚-金槍魚乾-金槍魚汁-85g-x6個",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-白肉金槍魚-金槍魚乾-金槍魚汁-85g-x6個",
  },
  {
    id: "wt-product-3",
    title: "CIAO 貓罐罐 - 雞肉, 和牛 85g　x 6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-3.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133836367.jpg?v=1583197671",
    description: "保存期 3年保証",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "和牛", "綠茶消臭成分", "罐罐", "雞肉"],
    handle: "ciao-貓罐罐-雞肉-和牛-85g-x-6",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-雞肉-和牛-85g-x-6",
  },
  {
    id: "wt-product-4",
    title: "CIAO　鮮肉杯　-　鰹魚, 金槍魚, 雞肉 （11歳起食用）70g x 6",
    price: 78.0,
    imageUrl: "/images/products/wt-product-4.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133863370.jpg?v=1585745407",
    description: "賞味期限2年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "綠茶消臭成分", "罐罐", "貓貓小食", "金槍魚", "雞肉", "鰹魚"],
    handle: "ciao-鮮肉杯-鰹魚-金槍魚-雞肉-11歳起食用-70g-x-6",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-鮮肉杯-鰹魚-金槍魚-雞肉-11歳起食用-70g-x-6",
  },
  {
    id: "wt-product-5",
    title: "CIAO　鮮肉杯　- 金槍魚 (11歳起食用)70g x 6",
    price: 78.0,
    imageUrl: "/images/products/wt-product-5.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133863387.jpg?v=1585745253",
    description: "賞味期限2年",
    vendor: "CIAO",
    tags: ["11歳起", "CIAO", "INABA", "綠茶消臭成分", "罐罐", "貓貓小食", "金槍魚"],
    handle: "ciao-鮮肉杯-金槍魚-11歳起食用70g-x-6",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-鮮肉杯-金槍魚-11歳起食用70g-x-6",
  },
  {
    id: "wt-product-6",
    title: "CIAO 貓罐罐 - 雞胸肉 鯛魚 鯛魚汁 85g x6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-6.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133062285.jpg?v=1583200947",
    description: "賞味期限3年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "綠茶消臭成分", "罐罐", "雞肉", "鯛"],
    handle: "ciao-貓罐罐-雞胸肉-鯛魚-鯛魚汁-85g-x6個",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-雞胸肉-鯛魚-鯛魚汁-85g-x6個",
  },
  {
    id: "wt-product-7",
    title: "CIAO 貓罐罐 - 白肉金槍魚, 白飯魚85g x6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-7.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133061158.jpg?v=1583200705",
    description: "賞味期限 3年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "白飯魚", "綠茶消臭成分", "罐罐", "貓貓小食", "金槍魚"],
    handle: "ciao-貓罐罐-白肉金槍魚-白飯魚85g-x6個",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-白肉金槍魚-白飯魚85g-x6個",
  },
  {
    id: "wt-product-8",
    title: "CIAO 貓罐罐 - 雞肉, 黃金槍魚, 木魚乾 85g x6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-8.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133061349.jpg?v=1583198665",
    description: "賞味期限 3年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "木魚乾", "綠茶消臭成分", "罐罐", "金槍魚", "雞肉"],
    handle: "ciao-貓罐罐-雞肉-黃金槍魚-木魚乾-85g",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-雞肉-黃金槍魚-木魚乾-85g",
  },
  {
    id: "wt-product-9",
    title: "CIAO 貓罐罐 - 白肉金槍魚、越光米 85g  x 6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-9.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133061172.jpg?v=1583202528",
    description: "賞味期限3年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "綠茶消臭成分", "罐罐", "金槍魚"],
    handle: "ciao-貓罐罐-白肉金槍魚-越光米-85g-x-6個",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-白肉金槍魚-越光米-85g-x-6個",
  },
  {
    id: "wt-product-10",
    title: "CIAO 貓罐罐 - 白肉金槍魚、鰹魚乾 85g  x 6個",
    price: 78.0,
    imageUrl: "/images/products/wt-product-10.jpg",
    sourceImageUrl: "https://cdn.shopify.com/s/files/1/0280/1428/0749/products/4901133062162.jpg?v=1583202365",
    description: "賞味期限3年",
    vendor: "CIAO",
    tags: ["CIAO", "INABA", "木魚乾", "綠茶消臭成分", "罐罐", "金槍魚"],
    handle: "ciao-貓罐罐-白肉金槍魚-鰹魚乾-85g-x-6個",
    productType: "貓罐罐",
    sourceUrl: "https://www.wt-japan.com/products/ciao-貓罐罐-白肉金槍魚-鰹魚乾-85g-x-6個",
  },
];

export function getWtJapanProductById(
  id: string | null | undefined,
): WtJapanProduct | null {
  if (!id) return null;
  return WT_JAPAN_PRODUCTS.find((p) => p.id === id) ?? null;
}
